### ISSUE TITLE
I can't install dependencies because cannot locate rosdep definition for [h6x_bringup_common] and [h6x_bringup_common]

### ISSUE THREAD

**Issue by airfanqie** [HarvestX/MG400_ROS2#243]
I just started learning ros2 and try Dobot MG400 with ROS2.
However, an error was encountered while following the steps to install the dependency.
The error is as follows:
mg400_bringup: Cannot locate rosdep definition for [h6x_bringup_common] 
mg400_joy: Cannot locate rosdep definition for [p9n_interface]
![Error reporting](https://github.com/HarvestX/MG400_ROS2/assets/148186255/d23c6fb2-8aa3-4c50-95f2-93e2d692f846)
The detailed error is shown in the screenshot.How should I solve this problem?
I really hope to get your reply. Thank you very much.

**Comment by ynyBonfennil** [comment]
`p9n_interface` is the ROS2 package of [this repository](https://github.com/HarvestX/PlayStation-JoyInterface-ROS2). You need to clone this repository to your workspace before running rosdep. Or, you can use [setup.bash](https://github.com/HarvestX/MG400_ROS2/blob/humble/setup.bash) to do all of them.

`h6x_bringup_common` is another ROS2 package but it turned out that it is not used in this repository, so I'll remove it by #255 .
